"""Allow only the sing-box configuration subset generated by this manager."""

import re
import stat
import uuid
from pathlib import Path

from sb_manager.privileged.errors import PrivilegedInputError

MAX_MANAGED_INBOUNDS = 128
MAX_LISTEN_PORT = 65535
PROFILE_TAG_PATTERN = re.compile(r"profile-[1-9][0-9]*")
TRUSTED_TLS_DIRECTORY = Path("/etc/sing-box-manager/tls")
ACME_DATA_DIRECTORY = Path("/var/lib/sing-box-manager/acme")


class ManagedConfigurationPolicy:
    """Reject sing-box capabilities outside product-generated profile artifacts."""

    def __init__(
        self,
        *,
        trusted_tls_directory: Path = TRUSTED_TLS_DIRECTORY,
        acme_data_directory: Path = ACME_DATA_DIRECTORY,
        expected_root_uid: int = 0,
    ) -> None:
        self._trusted_tls_directory = trusted_tls_directory
        self._acme_data_directory = acme_data_directory
        self._expected_root_uid = expected_root_uid

    def validate(self, document: dict[str, object]) -> None:
        fields = set(document)
        required = {"inbounds", "outbounds"}
        allowed = {*required, "certificate_providers"}
        if not required <= fields or not fields <= allowed:
            raise PrivilegedInputError(
                f"Managed configuration top-level fields must be {sorted(required)} "
                f"with optional certificate_providers"
            )
        outbounds = self._list(document["outbounds"], role="outbounds")
        if outbounds != [{"type": "direct", "tag": "direct"}]:
            raise PrivilegedInputError("Managed configuration permits only the direct outbound")
        inbounds = self._list(document["inbounds"], role="inbounds")
        if not 1 <= len(inbounds) <= MAX_MANAGED_INBOUNDS:
            raise PrivilegedInputError(
                f"Managed configuration requires 1 to {MAX_MANAGED_INBOUNDS} inbounds"
            )

        referenced_providers = self._validate_inbounds(inbounds)
        providers = self._list(
            document.get("certificate_providers", []),
            role="certificate_providers",
        )
        self._validate_providers(providers, referenced_providers=referenced_providers)

    def _validate_inbounds(self, inbounds: list[object]) -> dict[str, str]:
        referenced_providers: dict[str, str] = {}
        tags: set[str] = set()
        ports: set[int] = set()
        for raw_inbound in inbounds:
            inbound = self._untyped_object(raw_inbound, role="inbound")
            tag, port, inbound_provider = self._validate_inbound(inbound)
            if tag in tags:
                raise PrivilegedInputError(f"Managed inbound tag is duplicated: {tag}")
            if port in ports:
                raise PrivilegedInputError(f"Managed listen port is duplicated: {port}")
            tags.add(tag)
            ports.add(port)
            if inbound_provider is not None:
                provider_tag, server_name = inbound_provider
                if provider_tag in referenced_providers:
                    raise PrivilegedInputError(
                        f"Managed certificate provider is referenced twice: {provider_tag}"
                    )
                referenced_providers[provider_tag] = server_name

        return referenced_providers

    def _validate_providers(
        self,
        providers: list[object],
        *,
        referenced_providers: dict[str, str],
    ) -> None:
        actual_provider_tags: set[str] = set()
        for raw_provider in providers:
            provider_item = self._object(
                raw_provider,
                fields={"type", "tag", "domain", "email", "data_directory", "key_type"},
                role="ACME provider",
            )
            provider_tag = self._nonempty_string(provider_item["tag"], role="ACME provider tag")
            if provider_tag in actual_provider_tags:
                raise PrivilegedInputError(
                    f"Managed ACME provider tag is duplicated: {provider_tag}"
                )
            actual_provider_tags.add(provider_tag)
            expected_server_name = referenced_providers.get(provider_tag)
            if expected_server_name is None:
                raise PrivilegedInputError(
                    f"Managed ACME provider is not referenced by an inbound: {provider_tag}"
                )
            if provider_item["type"] != "acme" or provider_item["key_type"] != "p256":
                raise PrivilegedInputError("Managed ACME provider type or key type is invalid")
            domains = self._list(provider_item["domain"], role="ACME provider domain")
            if domains != [expected_server_name]:
                raise PrivilegedInputError(
                    "Managed ACME provider domain does not match inbound TLS"
                )
            self._nonempty_string(provider_item["email"], role="ACME provider email")
            if provider_item["data_directory"] != str(self._acme_data_directory):
                raise PrivilegedInputError(
                    f"Managed ACME data directory must be {self._acme_data_directory}"
                )
        if actual_provider_tags != set(referenced_providers):
            raise PrivilegedInputError("Managed certificate providers do not match inbound TLS")

    def _validate_inbound(
        self,
        inbound: dict[str, object],
    ) -> tuple[str, int, tuple[str, str] | None]:
        inbound_type = self._nonempty_string(inbound.get("type"), role="inbound type")
        if inbound_type == "vless":
            return self._validate_vless(inbound)
        if inbound_type == "vmess":
            return self._validate_vmess(inbound)
        validators = {
            "shadowsocks": self._validate_shadowsocks,
            "hysteria2": self._validate_hysteria2,
            "trojan": self._validate_password_tls,
            "anytls": self._validate_password_tls,
            "tuic": self._validate_tuic,
        }
        validator = validators.get(inbound_type)
        if validator is None:
            raise PrivilegedInputError(f"Unsupported managed inbound type: {inbound_type}")
        return validator(inbound)

    def _validate_common(
        self,
        inbound: dict[str, object],
        *,
        inbound_type: str,
        fields: set[str],
    ) -> tuple[str, int]:
        if set(inbound) != fields:
            raise PrivilegedInputError(
                f"Managed {inbound_type} inbound fields must be exactly {sorted(fields)}"
            )
        if inbound["type"] != inbound_type or inbound["listen"] != "::":
            raise PrivilegedInputError(
                f"Managed {inbound_type} inbound type or listen address is invalid"
            )
        tag = self._nonempty_string(inbound["tag"], role=f"{inbound_type} tag")
        if PROFILE_TAG_PATTERN.fullmatch(tag) is None:
            raise PrivilegedInputError(f"Managed inbound tag is invalid: {tag!r}")
        port = self._integer(inbound["listen_port"], role=f"{inbound_type} listen_port")
        if not 1 <= port <= MAX_LISTEN_PORT:
            raise PrivilegedInputError(f"Managed {inbound_type} listen port is invalid: {port}")
        return tag, port

    def _validate_vless(
        self,
        inbound: dict[str, object],
    ) -> tuple[str, int, tuple[str, str] | None]:
        tls = self._untyped_object(inbound.get("tls"), role="vless TLS")
        if "reality" in tls:
            tag, port = self._validate_common(
                inbound,
                inbound_type="vless",
                fields={"type", "tag", "listen", "listen_port", "users", "tls"},
            )
            self._validate_users(
                inbound["users"],
                role="vless Reality users",
                fields={"name", "uuid", "flow"},
                uuid_field="uuid",
                expected={"flow": "xtls-rprx-vision"},
            )
            self._validate_reality_tls(tls)
            return tag, port, None
        tag, port = self._validate_common(
            inbound,
            inbound_type="vless",
            fields={"type", "tag", "listen", "listen_port", "users", "tls", "transport"},
        )
        self._validate_users(
            inbound["users"],
            role="vless users",
            fields={"name", "uuid"},
            uuid_field="uuid",
        )
        self._validate_transport(inbound["transport"])
        return tag, port, self._validate_managed_tls(tls, profile_tag=tag)

    def _validate_vmess(
        self,
        inbound: dict[str, object],
    ) -> tuple[str, int, tuple[str, str] | None]:
        tag, port = self._validate_common(
            inbound,
            inbound_type="vmess",
            fields={"type", "tag", "listen", "listen_port", "users", "tls", "transport"},
        )
        self._validate_users(
            inbound["users"],
            role="vmess users",
            fields={"name", "uuid", "alterId"},
            uuid_field="uuid",
            expected={"alterId": 0},
        )
        self._validate_transport(inbound["transport"])
        tls = self._untyped_object(inbound["tls"], role="vmess TLS")
        return tag, port, self._validate_managed_tls(tls, profile_tag=tag)

    def _validate_shadowsocks(
        self,
        inbound: dict[str, object],
    ) -> tuple[str, int, tuple[str, str] | None]:
        tag, port = self._validate_common(
            inbound,
            inbound_type="shadowsocks",
            fields={
                "type",
                "tag",
                "listen",
                "listen_port",
                "network",
                "method",
                "password",
                "multiplex",
            },
        )
        if inbound["network"] != "tcp" or inbound["method"] != "2022-blake3-aes-128-gcm":
            raise PrivilegedInputError("Managed shadowsocks method or network is invalid")
        self._nonempty_string(inbound["password"], role="shadowsocks password")
        if inbound["multiplex"] != {"enabled": True}:
            raise PrivilegedInputError("Managed shadowsocks multiplex policy is invalid")
        return tag, port, None

    def _validate_hysteria2(
        self,
        inbound: dict[str, object],
    ) -> tuple[str, int, tuple[str, str] | None]:
        tag, port = self._validate_common(
            inbound,
            inbound_type="hysteria2",
            fields={
                "type",
                "tag",
                "listen",
                "listen_port",
                "users",
                "ignore_client_bandwidth",
                "tls",
            },
        )
        if inbound["ignore_client_bandwidth"] is not True:
            raise PrivilegedInputError("Managed hysteria2 bandwidth policy is invalid")
        self._validate_users(
            inbound["users"],
            role="hysteria2 users",
            fields={"name", "password"},
            secret_field="password",
        )
        tls = self._untyped_object(inbound["tls"], role="hysteria2 TLS")
        return tag, port, self._validate_managed_tls(tls, profile_tag=tag)

    def _validate_password_tls(
        self,
        inbound: dict[str, object],
    ) -> tuple[str, int, tuple[str, str] | None]:
        inbound_type = self._nonempty_string(inbound.get("type"), role="inbound type")
        tag, port = self._validate_common(
            inbound,
            inbound_type=inbound_type,
            fields={"type", "tag", "listen", "listen_port", "users", "tls"},
        )
        self._validate_users(
            inbound["users"],
            role=f"{inbound_type} users",
            fields={"name", "password"},
            secret_field="password",
        )
        tls = self._untyped_object(inbound["tls"], role=f"{inbound_type} TLS")
        return tag, port, self._validate_managed_tls(tls, profile_tag=tag)

    def _validate_tuic(
        self,
        inbound: dict[str, object],
    ) -> tuple[str, int, tuple[str, str] | None]:
        tag, port = self._validate_common(
            inbound,
            inbound_type="tuic",
            fields={
                "type",
                "tag",
                "listen",
                "listen_port",
                "users",
                "congestion_control",
                "zero_rtt_handshake",
                "tls",
            },
        )
        if inbound["congestion_control"] != "cubic" or inbound["zero_rtt_handshake"] is not False:
            raise PrivilegedInputError("Managed TUIC transport policy is invalid")
        self._validate_users(
            inbound["users"],
            role="tuic users",
            fields={"name", "uuid", "password"},
            uuid_field="uuid",
            secret_field="password",
        )
        tls = self._untyped_object(inbound["tls"], role="tuic TLS")
        return tag, port, self._validate_managed_tls(tls, profile_tag=tag)

    def _validate_users(  # noqa: PLR0913 - explicit schema fields are the trust boundary
        self,
        value: object,
        *,
        role: str,
        fields: set[str],
        uuid_field: str | None = None,
        secret_field: str | None = None,
        expected: dict[str, object] | None = None,
    ) -> None:
        users = self._list(value, role=role)
        if len(users) != 1:
            raise PrivilegedInputError(f"Managed {role} must contain exactly one user")
        user = self._object(users[0], fields=fields, role=role)
        self._nonempty_string(user["name"], role=f"{role} name")
        if uuid_field is not None:
            raw_uuid = self._nonempty_string(user[uuid_field], role=f"{role} UUID")
            try:
                uuid.UUID(raw_uuid)
            except ValueError as error:
                raise PrivilegedInputError(f"Managed {role} UUID is invalid") from error
        if secret_field is not None:
            self._nonempty_string(user[secret_field], role=f"{role} secret")
        for field, expected_value in (expected or {}).items():
            if user[field] != expected_value:
                raise PrivilegedInputError(f"Managed {role} field {field} is invalid")

    def _validate_reality_tls(self, tls: dict[str, object]) -> None:
        if set(tls) != {"enabled", "server_name", "reality"} or tls["enabled"] is not True:
            raise PrivilegedInputError("Managed Reality TLS fields are invalid")
        server_name = self._nonempty_string(tls["server_name"], role="Reality server_name")
        reality = self._object(
            tls["reality"],
            fields={"enabled", "handshake", "private_key", "short_id"},
            role="Reality settings",
        )
        if reality["enabled"] is not True:
            raise PrivilegedInputError("Managed Reality must be enabled")
        handshake = self._object(
            reality["handshake"],
            fields={"server", "server_port"},
            role="Reality handshake",
        )
        if handshake != {"server": server_name, "server_port": 443}:
            raise PrivilegedInputError("Managed Reality handshake is invalid")
        self._nonempty_string(reality["private_key"], role="Reality private key")
        short_ids = self._list(reality["short_id"], role="Reality short_id")
        if len(short_ids) != 1 or not isinstance(short_ids[0], str) or not short_ids[0]:
            raise PrivilegedInputError("Managed Reality short_id is invalid")

    def _validate_managed_tls(
        self,
        tls: dict[str, object],
        *,
        profile_tag: str,
    ) -> tuple[str, str] | None:
        if tls.get("enabled") is not True:
            raise PrivilegedInputError("Managed TLS must be enabled")
        server_name = self._nonempty_string(tls.get("server_name"), role="TLS server_name")
        if "certificate_provider" in tls:
            if set(tls) != {"enabled", "server_name", "certificate_provider"}:
                raise PrivilegedInputError("Managed ACME TLS fields are invalid")
            provider_tag = self._nonempty_string(
                tls["certificate_provider"],
                role="TLS certificate_provider",
            )
            if provider_tag != f"tls-{profile_tag}":
                raise PrivilegedInputError("Managed TLS provider tag does not match profile")
            return provider_tag, server_name
        if set(tls) != {"enabled", "server_name", "certificate_path", "key_path"}:
            raise PrivilegedInputError("Managed operator-file TLS fields are invalid")
        self._validate_tls_file(tls["certificate_path"], role="certificate", private=False)
        self._validate_tls_file(tls["key_path"], role="private key", private=True)
        return None

    def _validate_tls_file(self, value: object, *, role: str, private: bool) -> None:
        raw_path = self._nonempty_string(value, role=f"TLS {role} path")
        path = Path(raw_path)
        if not path.is_absolute() or ".." in path.parts:
            raise PrivilegedInputError(f"Managed TLS {role} must use an absolute normalized path")
        try:
            path.relative_to(self._trusted_tls_directory)
        except ValueError as error:
            raise PrivilegedInputError(
                f"Managed TLS {role} must be under trusted TLS directory "
                f"{self._trusted_tls_directory}"
            ) from error
        current = path
        while current != self._trusted_tls_directory:
            if current.is_symlink():
                raise PrivilegedInputError(f"Managed TLS {role} path contains a symlink: {current}")
            current = current.parent
        if self._trusted_tls_directory.is_symlink():
            raise PrivilegedInputError("Trusted TLS directory is a symlink")
        try:
            metadata = path.stat()
        except OSError as error:
            raise PrivilegedInputError(f"Managed TLS {role} file is unavailable: {path}") from error
        if not stat.S_ISREG(metadata.st_mode):
            raise PrivilegedInputError(f"Managed TLS {role} is not a regular file: {path}")
        if metadata.st_uid != self._expected_root_uid:
            raise PrivilegedInputError(f"Managed TLS {role} is not root-owned: {path}")
        mode = stat.S_IMODE(metadata.st_mode)
        if mode & 0o022 or (private and mode & 0o077):
            raise PrivilegedInputError(f"Managed TLS {role} permissions are unsafe: {path}")

    def _validate_transport(self, value: object) -> None:
        transport = self._untyped_object(value, role="transport")
        if transport.get("type") == "ws":
            item = self._object(
                transport,
                fields={"type", "path"},
                role="WebSocket transport",
            )
            path = self._nonempty_string(item["path"], role="WebSocket path")
            if not path.startswith("/"):
                raise PrivilegedInputError("Managed WebSocket path must start with /")
            return
        if transport.get("type") == "grpc":
            item = self._object(
                transport,
                fields={"type", "service_name"},
                role="gRPC transport",
            )
            self._nonempty_string(item["service_name"], role="gRPC service_name")
            return
        raise PrivilegedInputError(f"Unsupported managed transport: {transport.get('type')!r}")

    @staticmethod
    def _untyped_object(value: object, *, role: str) -> dict[str, object]:
        if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
            raise PrivilegedInputError(f"Managed {role} must be an object")
        return value

    @classmethod
    def _object(
        cls,
        value: object,
        *,
        fields: set[str],
        role: str,
    ) -> dict[str, object]:
        item = cls._untyped_object(value, role=role)
        if set(item) != fields:
            raise PrivilegedInputError(f"Managed {role} fields must be exactly {sorted(fields)}")
        return item

    @staticmethod
    def _list(value: object, *, role: str) -> list[object]:
        if not isinstance(value, list):
            raise PrivilegedInputError(f"Managed {role} must be a list")
        return value

    @staticmethod
    def _nonempty_string(value: object, *, role: str) -> str:
        if not isinstance(value, str) or not value:
            raise PrivilegedInputError(f"Managed {role} must be a non-empty string")
        return value

    @staticmethod
    def _integer(value: object, *, role: str) -> int:
        if not isinstance(value, int) or isinstance(value, bool):
            raise PrivilegedInputError(f"Managed {role} must be an integer")
        return value
